[window]
padding = { x = 0, y = 3 }
# dynamic_padding = true
dynamic_title = true

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true
